1740235955648	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms. (why=schedule)
1740237187416	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1740237187417	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740237187422	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms. (why=schedule)
1740237187426	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1740237187430	Sync.SyncScheduler	DEBUG	Woke from sleep.
1740237187432	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1740237187433	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1740237187433	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1740237189434	Sync.Service	DEBUG	User-Agent: Zen/1.7.6b (Linux x86_64) FxSync/1.137.0.20250207111303.desktop
1740237189434	Sync.Service	INFO	Starting sync at 2025-02-22 16:13:09 in browser session fm0rWKYN46Ot
1740237189437	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740237189438	Sync.Status	INFO	Resetting Status.
1740237189438	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1740237189439	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1740237189439	FirefoxAccounts	DEBUG	getOAuthToken enter
1740237189439	FirefoxAccounts	TRACE	getCachedToken returning cached token
1740237189439	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1740237189439	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1740237189442	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/266102437/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1740237189442	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1740237189442	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1740237189444	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1740237189445	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1740237189446	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
